/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package booksmart.Admin.panels;

import booksmart.connection.connection;
import java.awt.Color;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kisha
 */
public class StocksManagment extends javax.swing.JPanel {

    /**
     * Creates new form BookManagment
     */
    public StocksManagment() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StockId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel3.setFont(new java.awt.Font("Candara Light", 0, 20)); // NOI18N
        jLabel3.setText("Stock Managment");

        jLabel4.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        jLabel4.setText("Admin > Stock Managment");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Enter The Stock id to Activate or Deactivate :");

        StockId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StockIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StockIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StockIdKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(9, 9, 9));
        jButton1.setText("Activate / Deactivate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(13, 13, 13));
        jButton2.setText("Get A report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book Name", "Buy_Pr", "Sell_pr", "Qty", "Sold", "Last Update", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockId, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StockId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoadTable() {

        try {
            ResultSet rs = connection.Search("SELECT * FROM `stock` "
                    + "INNER JOIN `books` ON `stock`.`S_Book_id` = `books`.`Book_id` "
                    + "INNER JOIN `status` ON `stock`.`S_status` = `status`.`Status_ID`");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString("Stock_ID"));
                v.add(rs.getString("Book_Name"));
                v.add(rs.getString("Original_Price"));
                v.add(rs.getString("Public_Price"));
                v.add(rs.getString("Qty"));
                v.add(rs.getString("Sold"));
                v.add(rs.getString("Last_Stock_Update"));
                v.add(rs.getString("status"));
                dtm.addRow(v);

            }

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }

    }

    private void SearchTable() {

        String StockID = StockId.getText().trim();

        if (StockID.isBlank()) {
            LoadTable();
        } else {

            try {
                ResultSet rs = connection.Search("SELECT * FROM `stock` "
                        + "INNER JOIN `books` ON `stock`.`S_Book_id` = `books`.`Book_id` "
                        + "INNER JOIN `status` ON `stock`.`S_status` = `status`.`Status_ID` WHERE `stock`.`Stock_ID` LIKE '%" + StockID + "%'");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);

                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString("Stock_ID"));
                    v.add(rs.getString("Book_Name"));
                    v.add(rs.getString("Original_Price"));
                    v.add(rs.getString("Public_Price"));
                    v.add(rs.getString("Qty"));
                    v.add(rs.getString("Sold"));
                    v.add(rs.getString("Last_Stock_Update"));
                    v.add(rs.getString("status"));
                    dtm.addRow(v);

                    if (rs.getInt("S_status") == 1) {
                        jButton1.setText("Deactivate Stock");
                        jButton1.setBackground(Color.red);
                    } else {
                        jButton1.setText("Activate Stock");
                        jButton1.setBackground(Color.green);
                    }

                }

            } catch (java.sql.SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoadTable();
        try {
            InputStream filePath = getClass()
                    .getClassLoader()
                    .getResourceAsStream("booksmart/Report/Booksmart_Stock.jasper");
            HashMap<String, Object> parameters = new HashMap<>();

            JRTableModelDataSource jrTableModelDataSource = new JRTableModelDataSource(jTable1.getModel());
            JasperPrint fillReport = JasperFillManager.fillReport(filePath, parameters, jrTableModelDataSource);
            JasperViewer.viewReport(fillReport, false);
        } catch (JRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void StockIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockIdKeyTyped
        SearchTable();
    }//GEN-LAST:event_StockIdKeyTyped

    private void StockIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockIdKeyReleased
        SearchTable();
    }//GEN-LAST:event_StockIdKeyReleased

    private void StockIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockIdKeyPressed
        SearchTable();
    }//GEN-LAST:event_StockIdKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String StockID = StockId.getText().trim();

        if (StockID.isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Please Enter The Stock Id",
                    "Stock managment",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ResultSet rs = connection.Search("SELECT * FROM `stock` WHERE `stock`.`Stock_ID` = '" + StockID + "'");

            if (rs.next()) {

                int StatusId;
                String status;

                if (rs.getInt("S_status") == 1) {
                    StatusId = 0;
                    status = "Deactivated";
                } else {
                    StatusId = 1;
                    status = "Activated";
                }

                connection.IUD("UPDATE `stock` SET `S_status` = '" + StatusId + "' WHERE `stock`.`Stock_ID` = '" + StockID + "'");

                JOptionPane.showMessageDialog(null,
                        "Stock Has Been" + status,
                        "Stock managment",
                        JOptionPane.PLAIN_MESSAGE);
                LoadTable();
                SearchTable();

            } else {
                JOptionPane.showMessageDialog(null,
                        "Please Enter The Correct ID",
                        "Stock managment",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,
                    "Please Contact The Devoloper",
                    "Stock managment",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StockId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
