app.name=BookSmart
app.db.name=booksmart
app.db.username=root
app.db.host=localhost
app.db.pw=kishan2007
#app.db.mysql_path=C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql
#app.db.mysqldump_path=C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump
app.theme=LIGHT